Rollno = input('Enter Roll No:')
Group = input('Enter group name:')
Reg_no = input('Enter Registration No:')
Cert_no = input('Enter Certificate No:')
Name = input('Enter Candidate Name:')
Father_name = input('Enter Father name:')
Institution_name = input('Enter Institution name:')
Identification_mark = input('Enter mark of identification:')
English_obtmark = input('Enter English marks:')
Urdu_obtmark = input('Enter Urdu marks:')
Islamiyat_obtmark = input('Enter Islamiyat marks:')
Pakstudies_obtmark = input('Enter Pak studies marks:')
Maths_obtmark = input('Enter Mathematics marks:')
Physics_obtmark = input('Enter Physics marks:')
Chemistry_obtmark = input('Enter Chemistry marks:')
Biology_obtmark = input('Enter Biology marks:')
Total_obtmark = English_obtmark + Urdu_obtmark + Islamiyat_obtmark + Pakstudies_obtmark + Maths_obtmark + Physics_obtmark + Chemistry_obtmark + Biology_obtmark
P=Total_obtmark*100
Percentage = P/1050
Birth_Date = input('Enter Date of Birth:')
Issue_Date = input('Enter Issue date:')
print('      FEDERAL BOARD OF INTERMEDIATE AND SECONDARY EDUCATION, ISLAMABAD       ')
print('              SECONDARY SCHOOL CERTIFICATE (SSC) EXAMINATION                 ')
print('                                                                             ')
print('                              RESULT CARD                                    ')
print('                        ANNUAL EXAMINATION 2022                              ')
print('                                                                             ')
print('Roll No.'+'               '+repr(Rollno))
print('Group'+'                  '+(Group))
print('Registration No.'+'       '+repr(Reg_no))
print('Certificate No.'+'        '+repr(Cert_no))
print('                                                                             ')
print('                                                                             ')
print((Name)+'  '+'S/D of'+'  '+(Father_name)+'  '+'of institution'+'  '+(Institution_name)+' '+'has'+'\n'+ 'secured the marks shown against each subject in the Secondary School Certificate'+'\n'+ '(SSC) Examination held in the month(s) of March/April.')
print('Mark of Identification'+'  '+(Identification_mark))
print('                                                                             ')
print('      Subject(s)           Subj. Max Marks     Obtained Marks     Pass/Fail   ')
print('ENGLISH (COMPULSORY)'+'             '+'150'+'                '+repr(English_obtmark)+'              '+('PASS'if English_obtmark>50 else 'COMP'))
print('URDU (COMPULSORY)'+'                '+'150'+'                '+repr(Urdu_obtmark)+'              '+('PASS'if Urdu_obtmark>50 else 'COMP'))
print('ISLAMIYAT (COMPULSORY)'+'           '+'075'+'                '+repr(Islamiyat_obtmark)+'               '+('PASS'if Islamiyat_obtmark>25 else 'COMP'))
print('PAKISTAN STUDIES'+'                 '+'075'+'                '+repr(Pakstudies_obtmark)+'               '+('PASS'if Pakstudies_obtmark>25 else 'COMP'))
print('MATHEMATICS'+'                      '+'150'+'                '+repr(Maths_obtmark)+'              '+('PASS'if Maths_obtmark>50 else 'COMP'))
print('PHYSICS'+'                          '+'150'+'                '+repr(Physics_obtmark)+'              '+('PASS'if Physics_obtmark>50 else 'COMP'))
print('CHEMISTRY'+'                        '+'150'+'                '+repr(Chemistry_obtmark)+'              '+('PASS'if Chemistry_obtmark>50 else 'COMP'))
print('BIOLOGY'+'                          '+'150'+'                '+repr(Biology_obtmark)+'              '+('PASS'if Biology_obtmark>50 else 'COMP'))
print('                                                                             ')
print('Total Marks Obtained'+'    '+repr(Total_obtmark)+'/1050')
print('Percentage'+'              '+repr(Percentage)+' '+'%')
if Percentage>=80:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'A1')
elif Percentage >=70:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'A')
elif Percentage >=60:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'B')
elif Percentage >=50:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'C')
elif Percentage >=40:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'D')
elif Percentage >=33:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'E')
else:
    print('General Remarks'+'         '+'The Candidate has awarded Grade'+' '+'F')
print('Date of Birth'+'           '+Birth_Date)
print('Islamabad Dated'+'         '+Issue_Date)
print('                                                      ______________________ ')
print('                                                    CONTROLLER OF EXAMINATIONS')